[package]
name = "simpliste"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["F.X.P."]
license = "MIT"
description = "Create customized list styles and bibliography display styles as an alternative to Typst' s builtin `bibliography` function."